include: package:flutter_lints/flutter.yaml

dart_code_metrics:
  extends:
    - package:dart_code_metrics_presets/all.yaml
    - package:dart_code_metrics_presets/pub.yaml
  rules:
    # style
    arguments-ordering: false
    avoid-adjacent-strings: false
    avoid-inferrable-type-arguments: false
    avoid-returning-cascades: false
    avoid-similar-names:
      exclude:
        - test/**
    enum-constants-ordering: false
    format-comment:
      only-doc-comments: true
    member-ordering: false
    newline-before-case: false
    newline-before-return: false
    parameters-ordering: false
    prefer-boolean-prefixes: false
    prefer-correct-callback-field-name: false
    prefer-correct-identifier-length:
        exceptions: ['i', 'x', 'y', 'a', 'b', 't']
        min-identifier-length: 3
        max-identifier-length: 40
    prefer-extracting-function-callbacks:
      allowed-line-count: 5
    prefer-named-parameters:
      max-number: 3
    prefer-returning-conditional-expressions: false
    prefer-single-declaration-per-file: false
    unnecessary-trailing-comma: false

    # style (flutter)
    prefer-single-widget-per-file:
      ignore-private-widgets: true
    prefer-widget-private-members: false

    # warning
    avoid-collection-mutating-methods: false
    avoid-continue: false
    avoid-duplicate-collection-elements: false
    avoid-late-keyword: false
    avoid-long-files:
      exclude:
        - test/**
    avoid-long-functions:
      exclude:
        - test/**
      ignored-names:
        - paint
        - toImage
    avoid-non-null-assertion: false
    avoid-nullable-parameters-with-default-values: false # wrong rule
    avoid-passing-default-values: false
    avoid-self-compare:
      exclude:
        - test/**
    avoid-shadowing:
      ignore-parameters: true
    no-equal-arguments: false
    no-magic-number: false
    no-magic-string:
      exclude:
        - test/**
      allow-only-once: true
    prefer-addition-subtraction-assignments: false
    prefer-correct-throws: false
    prefer-match-file-name: false
    prefer-moving-to-variable:
      exclude:
        - test/**
    prefer-overriding-parent-equality:
      exclude:
        - test/**

    # needs new dart features
    prefer-class-destructuring: false
    prefer-abstract-final-static-class: false

  # warning (pubspec)
  pubspec-rules:
    prefer-caret-version-syntax: false
    prefer-publish-to-none: false
